[package]
name = "auto-journal-writing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.13.0"
dotenv = "0.15.0"
tokio = { version = "1.31.0", features = ["macros"] }
